# Generated by Django 2.1.3 on 2018-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenpoll',
            name='poll_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
