# Generated by Django 2.1.3 on 2018-12-09 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_takenpoll_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenpoll',
            name='time_taken',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 22, 27, 11, 958064, tzinfo=utc)),
        ),
    ]
